# Generated by Django 2.0 on 2018-10-04 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userone',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_branch', to='cust_auth.InstituteBranch'),
        ),
        migrations.AlterField(
            model_name='userone',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 4, 11, 15, 54, 228989), max_length=8),
        ),
    ]
