# Generated by Django 2.0 on 2018-10-04 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0002_auto_20181004_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userone',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 4, 11, 44, 8, 8628), max_length=8),
        ),
    ]
