# Generated by Django 2.0 on 2018-10-04 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0003_auto_20181004_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userone',
            options={},
        ),
        migrations.AddField(
            model_name='userone',
            name='enrollment',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userone',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 4, 12, 3, 54, 208071), max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='userone',
            unique_together={('enrollment', 'branch')},
        ),
    ]
