# Generated by Django 2.0 on 2018-10-04 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0004_auto_20181004_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userone',
            name='dob',
            field=models.DateField(default=datetime.datetime(2018, 10, 4, 12, 4, 7, 692948), max_length=8),
        ),
    ]
