# Generated by Django 2.0 on 2018-10-06 10:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cust_auth', '0005_auto_20181004_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mobile', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')])),
                ('enrollment', models.CharField(max_length=30)),
                ('course', models.CharField(choices=[('be', 'B-TECH'), ('mba', 'MBA'), ('pharmacy', 'PHARMACY')], default='be', max_length=6)),
                ('dob', models.DateField(default=datetime.datetime(2018, 10, 6, 10, 18, 0, 864977), max_length=8)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=6)),
                ('address', models.CharField(max_length=15)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_branch', to='cust_auth.InstituteBranch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userone',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userone',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userone',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userone',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Userone',
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('enrollment', 'branch')},
        ),
    ]
