# Generated by Django 2.0 on 2018-10-11 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cust_auth', '0015_auto_20181009_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesTransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('payment_id', models.CharField(max_length=200)),
                ('payer_id', models.CharField(max_length=200)),
                ('payment_create_date', models.DateField(null=True)),
                ('payment_fees_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_dode_fees_type', to='cust_auth.InstituteFees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transacction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
