# Generated by Django 2.0 on 2018-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0016_feestransactiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestransactiondetails',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
