# Generated by Django 2.0 on 2018-10-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0018_auto_20181011_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutefees',
            name='fees_type',
            field=models.CharField(max_length=20),
        ),
    ]
