# Generated by Django 2.0 on 2018-10-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0019_auto_20181012_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutefees',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
    ]
