# Generated by Django 2.0 on 2018-10-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0020_institutefees_fees_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutefees',
            name='fees_paid',
        ),
    ]
