# Generated by Django 2.0 on 2018-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0021_remove_institutefees_fees_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestransactiondetails',
            name='payment_create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
