# Generated by Django 2.0 on 2018-10-12 06:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0022_auto_20181012_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestransactiondetails',
            name='payment_response',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
