# Generated by Django 2.0 on 2018-10-12 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0023_feestransactiondetails_payment_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestransactiondetails',
            name='id',
        ),
        migrations.AddField(
            model_name='feestransactiondetails',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
