# Generated by Django 2.0 on 2018-10-12 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0025_auto_20181012_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestransactiondetails',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
