# Generated by Django 2.0 on 2018-10-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0027_auto_20181012_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestransactiondetails',
            name='u_id',
        ),
    ]
