# Generated by Django 2.0 on 2018-10-15 04:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0029_remove_feestransactiondetails_payment_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestransactiondetails',
            name='payment_create_date',
        ),
        migrations.AddField(
            model_name='feestransactiondetails',
            name='payment_response',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
