# Generated by Django 2.0 on 2018-10-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0009_auto_20181006_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('be', 'B-TECH'), ('mba', 'MBA'), ('pharmacy', 'PHARMACY')], default='be', max_length=8),
        ),
    ]
