# Generated by Django 2.0 on 2018-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0011_passwordresettokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutefees',
            name='fees_type',
            field=models.CharField(choices=[('admission', 'ADMISSION'), ('exam', 'EXAM'), ('hostel', 'HOSTEL'), ('transportation', 'TRANSPORTATION')], default='admission', max_length=20),
        ),
    ]
