# Generated by Django 2.0 on 2018-10-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_auth', '0013_auto_20181009_0617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutefees',
            unique_together=set(),
        ),
    ]
